/**
 * Venida Platform
 * Free Open Source Software
 * Auto Generated by SEJE - Digital
 */

import { Knex } from "knex";

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex: Knex) {
    return await knex.schema.createTable("user", function (table: any) {
        table.bigIncrements();
        table.string('name').notNullable();
        table.string('email', 128).notNullable();
        table.string('password').notNullable();
        table.boolean('is_active').notNullable();
        table.bigInteger('created_at').defaultTo(Math.floor(Date.now()/1000));
        table.bigInteger('updated_at');
    });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex: Knex) {
    return await knex.schema.dropTable("user");
};